[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "molecular_dynamics"
version = "0.1.0"

[project.scripts]
mdsim = "molecular_dynamics.simulator:main"